import {readFile, writeFile} from 'node:fs/promises';
import openapiTS, {astToString} from 'openapi-typescript';
import {operations} from './operations.js';

interface Parameter {name: string; in: string; required?: boolean; schema?: {type?: string}}
interface Schema {required?: string[]; properties?: Record<string, Schema>}
interface Operation {
  summary?: string;
  parameters?: Parameter[];
  requestBody?: {required?: boolean; content: Record<string, {schema: Schema}>};
  responses: Record<string, {content?: Record<string, unknown>}>;
}
const source = new URL('../zai-openapi.json', import.meta.url);
const spec = JSON.parse(await readFile(source, 'utf8')) as {paths: Record<string, Record<string, Operation>>};
const methods = new Set(['get', 'post', 'put', 'patch', 'delete', 'head', 'options', 'trace']);
const expected = Object.entries(spec.paths).flatMap(([path, item]) => Object.keys(item).filter(method => methods.has(method)).map(method => `${method} ${path}`)).sort();
const actual = operations.map(([, , method, path]) => `${method} ${path}`).sort();
const names = operations.map(([group, name]) => `${group}.${name}`);
if (new Set(names).size !== names.length || JSON.stringify(actual) !== JSON.stringify(expected)) {
  throw new Error(`Operation mapping mismatch. Missing: ${expected.filter(key => !actual.includes(key)).join(', ')}; extra/duplicate: ${actual.filter((key, i) => !expected.includes(key) || actual.indexOf(key) !== i).join(', ')}`);
}
const generated = '/** Generated by pnpm generate:api from zai-openapi.json. Do not edit directly. */\n';
const aliases: string[] = [];
const groups = new Map<string, string[]>();
const metadata: object[] = [];
const upper = (value: string) => value[0]!.toUpperCase() + value.slice(1);
const camel = (value: string) => value.replace(/_([a-z])/g, (_, letter: string) => letter.toUpperCase());
const q = JSON.stringify;

for (const [group, name, method, path] of operations) {
  const op = spec.paths[path]![method]!;
  const typeName = upper(group) + upper(name);
  const ref = `paths[${q(path)}][${q(method)}]`;
  const parameters = op.parameters ?? [];
  const pathParams = [...path.matchAll(/\{([^}]+)\}/g)].map(match => match[1]!);
  const query = parameters.filter(parameter => parameter.in === 'query');
  const content = op.requestBody?.content;
  const isUpload = !!content?.['multipart/form-data'] && !content['application/json'];
  const isBundle = !!content?.['multipart/form-data'] && !!content['application/json'];
  const isSend = group === 'messages' && name === 'send';
  const statuses = Object.keys(op.responses).filter(status => /^2\d\d$/.test(status));
  const binary = statuses.some(status => !!op.responses[status]?.content?.['application/octet-stream']);
  const response = binary ? 'Blob' : statuses.map(status => `${ref}['responses'][${status}]['content']['application/json']`).join(' | ');
  aliases.push(`export type ${typeName}Response = ${response};`);
  const args = pathParams.map(param => `${camel(param)}: string`);
  const fields = [`method: ${q(method)}`, `path: ${q(path)}`, `successStatuses: [${statuses.join(', ')}]`];
  if (pathParams.length) fields.push(`pathParams: {${pathParams.map(param => `${q(param)}: ${camel(param)}`).join(', ')}}`);
  if (query.length) {
    aliases.push(`export type ${typeName}Query = NonNullable<${ref}['parameters']['query']>;`);
    args.push(`query${query.some(param => param.required) ? '' : '?'}: ${typeName}Query`);
    fields.push('query');
  }
  if (content) {
    const jsonType = `NonNullable<${ref}['requestBody']>['content']['application/json']`;
    const multipartType = `NonNullable<${ref}['requestBody']>['content']['multipart/form-data']`;
    let bodyType = isUpload ? `Omit<${multipartType}, 'file'> & {file: ZAIUploadFile}` : jsonType;
    if (isBundle) bodyType = `${jsonType} | (Omit<${multipartType}, 'bundle'> & {bundle: ZAIUploadFile})`;
    if (isSend) bodyType = `Omit<${jsonType}, 'stream'>`;
    aliases.push(`export type ${typeName}Input = ${bodyType};`);
    const required = op.requestBody?.required || Object.values(content).some(media => media.schema.required?.length);
    args.push(`input${required ? '' : '?'}: ${typeName}Input`);
    fields.push(isSend ? 'body: {...input, stream: false}' : 'body: input');
    if (isUpload || isBundle) fields.push(`encoding: '${isUpload ? 'multipart' : 'bundle'}'`);
  }
  if (binary) fields.push("responseType: 'blob'");
  args.push('options?: ZAIRequestOptions');
  fields.push('options');
  const request = `transport.request<${typeName}Response>({${fields.join(', ')}})`;
  const methodSource = group === 'models'
    ? `async ${name}(${args.join(', ')}): Promise<${typeName}Response> {\n      const result = await ${request};\n      const normalized = Array.isArray(result) ? {models: result} : result;\n      if (!normalized || !Array.isArray(normalized.models) || normalized.models.some(model => !model || typeof model.id !== 'string')) throw new ZAIClientError('invalid-response', 'Invalid model list response.');\n      return normalized;\n    }`
    : `${name}(${args.join(', ')}): Promise<${typeName}Response> { return ${request}; }`;
  const members = groups.get(group) ?? [];
  members.push(`/** ${op.summary?.replace(/\*\//g, '') ?? name} */\n    ${methodSource}`);
  if (isSend) {
    const streamFields = fields.map(field => field === 'body: {...input, stream: false}' ? 'body: {...input, stream: true}' : field);
    streamFields.push("responseType: 'stream'");
    members.push(`/** Stream full SSE chunks. A done event marks successful completion. */\n    async stream(${args.join(', ')}): Promise<AsyncIterableIterator<ZAIStreamEvent>> { return parseZAIStream(await transport.request<Response>({${streamFields.join(', ')}}), options?.signal); }`);
  }
  groups.set(group, members);
  metadata.push({group, name, method, path, pathParams, query: query.map(param => param.name), hasBody: !!content, encoding: isUpload ? 'multipart' : isBundle ? 'bundle' : 'json', responseType: binary ? 'blob' : 'json', statuses: statuses.map(Number)});
}

const client = generated + `import type {paths} from './schema.js';
import type {CreateZAIClientOptions, ZAIRequestOptions, ZAIUploadFile} from './types.js';
import {createTransport} from './transport.js';
import {parseZAIStream, type ZAIStreamEvent} from './stream.js';
import {ZAIClientError} from './errors.js';
import {runZAIDoctor, type ZAIDoctorOptions, type ZAIDoctorResult} from './doctor.js';

${aliases.join('\n')}

/** Create a stateless API client. Lists retain their server pagination envelopes. */
export function createZAIClient(options: CreateZAIClientOptions) {
  const transport = createTransport(options);
  const baseUrl = new URL(options.baseUrl, globalThis.location?.href).href;
  const client = {
${[...groups].map(([name, members]) => `  ${name}: {\n    ${members.join(',\n    ')}\n  }`).join(',\n')}
  };
  return {
    ...client,
    /** Check connection and capabilities; opt into a temporary chat probe with chat: true. */
    doctor(options?: ZAIDoctorOptions): Promise<ZAIDoctorResult> { return runZAIDoctor(client, baseUrl, options); },
  };
}

export type ZAIClient = ReturnType<typeof createZAIClient>;
`;
const schema = astToString(await openapiTS(source, {emptyObjectsUnknown: true}));
const outputs = new Map([
  ['src/schema.ts', schema],
  ['src/client.ts', client],
  ['src/operations.ts', generated + `/** Operation manifest used by contract tests and diagnostics. */\nexport const ZAI_OPERATIONS = ${JSON.stringify(metadata, null, 2)} as const;\n`],
]);
const check = process.argv.includes('--check');
for (const [path, text] of outputs) {
  const file = new URL(`../${path}`, import.meta.url);
  if (check) {
    if (await readFile(file, 'utf8').catch(() => '') !== text) throw new Error(`${path} is stale. Run pnpm generate:api.`);
  } else await writeFile(file, text);
}
console.log(`${check ? 'Checked' : 'Generated'} ${operations.length} operations from zai-openapi.json.`);
