/** Generated by pnpm generate:api from zai-openapi.json. Do not edit directly. */
import type {paths} from './schema.js';
import type {CreateZAIClientOptions, ZAIRequestOptions, ZAIUploadFile} from './types.js';
import {createTransport} from './transport.js';
import {parseZAIStream, type ZAIStreamEvent} from './stream.js';
import {ZAIClientError} from './errors.js';
import {runZAIDoctor, type ZAIDoctorOptions, type ZAIDoctorResult} from './doctor.js';

export type AgentsListResponse = paths["/agents"]["get"]['responses'][200]['content']['application/json'];
export type AgentsCreateResponse = paths["/agents"]["post"]['responses'][201]['content']['application/json'];
export type AgentsCreateInput = NonNullable<paths["/agents"]["post"]['requestBody']>['content']['application/json'];
export type AgentsGetResponse = paths["/agents/{agent_id}"]["get"]['responses'][200]['content']['application/json'];
export type AgentsUpdateResponse = paths["/agents/{agent_id}"]["put"]['responses'][200]['content']['application/json'];
export type AgentsUpdateInput = NonNullable<paths["/agents/{agent_id}"]["put"]['requestBody']>['content']['application/json'];
export type AgentsDeleteResponse = paths["/agents/{agent_id}"]["delete"]['responses'][200]['content']['application/json'];
export type AgentsDeleteInput = NonNullable<paths["/agents/{agent_id}"]["delete"]['requestBody']>['content']['application/json'];
export type ExecutorGetPublicKeyResponse = paths["/agents/{agent_id}/executor/public-key"]["get"]['responses'][200]['content']['application/json'];
export type ExecutorRotatePublicKeyResponse = paths["/agents/{agent_id}/executor/rotate"]["post"]['responses'][200]['content']['application/json'];
export type ExecutorGetAgentsMarkdownResponse = paths["/agents/{agent_id}/workspaces/{workspace_id}/executor/AGENTS.md"]["get"]['responses'][200]['content']['application/json'];
export type ExecutorUpdateAgentsMarkdownResponse = paths["/agents/{agent_id}/workspaces/{workspace_id}/executor/AGENTS.md"]["put"]['responses'][200]['content']['application/json'];
export type ExecutorUpdateAgentsMarkdownInput = NonNullable<paths["/agents/{agent_id}/workspaces/{workspace_id}/executor/AGENTS.md"]["put"]['requestBody']>['content']['application/json'];
export type WorkspacesListResponse = paths["/agents/{agent_id}/workspaces"]["get"]['responses'][200]['content']['application/json'];
export type WorkspacesCreateResponse = paths["/agents/{agent_id}/workspaces"]["post"]['responses'][201]['content']['application/json'];
export type WorkspacesCreateInput = NonNullable<paths["/agents/{agent_id}/workspaces"]["post"]['requestBody']>['content']['application/json'];
export type WorkspacesGetResponse = paths["/agents/{agent_id}/workspaces/{workspace_id}"]["get"]['responses'][200]['content']['application/json'];
export type WorkspacesUpdateResponse = paths["/agents/{agent_id}/workspaces/{workspace_id}"]["patch"]['responses'][200]['content']['application/json'];
export type WorkspacesUpdateInput = NonNullable<paths["/agents/{agent_id}/workspaces/{workspace_id}"]["patch"]['requestBody']>['content']['application/json'];
export type WorkspacesDeleteResponse = paths["/agents/{agent_id}/workspaces/{workspace_id}"]["delete"]['responses'][200]['content']['application/json'];
export type RepositoriesListResponse = paths["/agents/{agent_id}/workspaces/{workspace_id}/repos"]["get"]['responses'][200]['content']['application/json'];
export type RepositoriesCreateResponse = paths["/agents/{agent_id}/workspaces/{workspace_id}/repos"]["post"]['responses'][201]['content']['application/json'];
export type RepositoriesCreateInput = NonNullable<paths["/agents/{agent_id}/workspaces/{workspace_id}/repos"]["post"]['requestBody']>['content']['application/json'];
export type RepositoriesGetResponse = paths["/agents/{agent_id}/workspaces/{workspace_id}/repos/{repository_id}"]["get"]['responses'][200]['content']['application/json'];
export type RepositoriesUpdateResponse = paths["/agents/{agent_id}/workspaces/{workspace_id}/repos/{repository_id}"]["patch"]['responses'][200]['content']['application/json'];
export type RepositoriesUpdateInput = NonNullable<paths["/agents/{agent_id}/workspaces/{workspace_id}/repos/{repository_id}"]["patch"]['requestBody']>['content']['application/json'];
export type RepositoriesDeleteResponse = paths["/agents/{agent_id}/workspaces/{workspace_id}/repos/{repository_id}"]["delete"]['responses'][200]['content']['application/json'];
export type RepositoriesListFilesResponse = paths["/agents/{agent_id}/workspaces/{workspace_id}/repos/{repository_id}/files"]["get"]['responses'][200]['content']['application/json'];
export type RepositoriesReadFileResponse = paths["/agents/{agent_id}/workspaces/{workspace_id}/repos/{repository_id}/files/content"]["get"]['responses'][200]['content']['application/json'];
export type RepositoriesReadFileQuery = NonNullable<paths["/agents/{agent_id}/workspaces/{workspace_id}/repos/{repository_id}/files/content"]["get"]['parameters']['query']>;
export type RepositoriesDownloadFileResponse = Blob;
export type RepositoriesDownloadFileQuery = NonNullable<paths["/agents/{agent_id}/workspaces/{workspace_id}/repos/{repository_id}/files/download"]["get"]['parameters']['query']>;
export type SessionsListResponse = paths["/sessions"]["get"]['responses'][200]['content']['application/json'];
export type SessionsListQuery = NonNullable<paths["/sessions"]["get"]['parameters']['query']>;
export type SessionsListForAgentResponse = paths["/agents/{agent_id}/sessions"]["get"]['responses'][200]['content']['application/json'];
export type SessionsListForAgentQuery = NonNullable<paths["/agents/{agent_id}/sessions"]["get"]['parameters']['query']>;
export type SessionsCreateResponse = paths["/agents/{agent_id}/sessions"]["post"]['responses'][201]['content']['application/json'];
export type SessionsCreateInput = NonNullable<paths["/agents/{agent_id}/sessions"]["post"]['requestBody']>['content']['application/json'];
export type SessionsGetResponse = paths["/sessions/{session_id}"]["get"]['responses'][200]['content']['application/json'];
export type SessionsUpdateResponse = paths["/sessions/{session_id}"]["put"]['responses'][200]['content']['application/json'];
export type SessionsUpdateInput = NonNullable<paths["/sessions/{session_id}"]["put"]['requestBody']>['content']['application/json'];
export type SessionsDeleteResponse = paths["/sessions/{session_id}"]["delete"]['responses'][200]['content']['application/json'];
export type SessionsResetContextResponse = paths["/sessions/{session_id}/context/reset"]["post"]['responses'][200]['content']['application/json'];
export type SessionsGenerateTitleResponse = paths["/sessions/{session_id}/generate-title"]["post"]['responses'][200]['content']['application/json'];
export type SessionsListFilesResponse = paths["/sessions/{session_id}/files"]["get"]['responses'][200]['content']['application/json'];
export type SessionsListFilesQuery = NonNullable<paths["/sessions/{session_id}/files"]["get"]['parameters']['query']>;
export type SessionsReadFileResponse = paths["/sessions/{session_id}/files/content"]["get"]['responses'][200]['content']['application/json'];
export type SessionsReadFileQuery = NonNullable<paths["/sessions/{session_id}/files/content"]["get"]['parameters']['query']>;
export type SessionsDownloadFileResponse = Blob;
export type SessionsDownloadFileQuery = NonNullable<paths["/sessions/{session_id}/files/download"]["get"]['parameters']['query']>;
export type SessionsUploadFileResponse = paths["/sessions/{session_id}/files/upload"]["post"]['responses'][200]['content']['application/json'];
export type SessionsUploadFileInput = Omit<NonNullable<paths["/sessions/{session_id}/files/upload"]["post"]['requestBody']>['content']['multipart/form-data'], 'file'> & {file: ZAIUploadFile};
export type SessionsGenerateImagesResponse = paths["/sessions/{session_id}/images/generations"]["post"]['responses'][200]['content']['application/json'];
export type SessionsGenerateImagesInput = NonNullable<paths["/sessions/{session_id}/images/generations"]["post"]['requestBody']>['content']['application/json'];
export type MessagesSendResponse = paths["/sessions/{session_id}/messages"]["post"]['responses'][200]['content']['application/json'];
export type MessagesSendInput = Omit<NonNullable<paths["/sessions/{session_id}/messages"]["post"]['requestBody']>['content']['application/json'], 'stream'>;
export type MessagesListResponse = paths["/sessions/{session_id}/messages"]["get"]['responses'][200]['content']['application/json'];
export type MessagesGetResponse = paths["/messages/{message_id}"]["get"]['responses'][200]['content']['application/json'];
export type MessagesDeleteResponse = paths["/messages/{message_id}"]["delete"]['responses'][200]['content']['application/json'];
export type MessagesDeleteAllResponse = paths["/sessions/{session_id}/messages"]["delete"]['responses'][200]['content']['application/json'];
export type AgentSkillsListResponse = paths["/agents/{agent_id}/skills"]["get"]['responses'][200]['content']['application/json'];
export type AgentSkillsMountResponse = paths["/agents/{agent_id}/skills"]["post"]['responses'][201]['content']['application/json'];
export type AgentSkillsMountInput = NonNullable<paths["/agents/{agent_id}/skills"]["post"]['requestBody']>['content']['application/json'];
export type AgentSkillsUpdateResponse = paths["/agents/{agent_id}/skills/{skill_id}"]["patch"]['responses'][200]['content']['application/json'];
export type AgentSkillsUpdateInput = NonNullable<paths["/agents/{agent_id}/skills/{skill_id}"]["patch"]['requestBody']>['content']['application/json'];
export type AgentSkillsUnmountResponse = paths["/agents/{agent_id}/skills/{skill_id}"]["delete"]['responses'][200]['content']['application/json'];
export type SkillsListResponse = paths["/skills"]["get"]['responses'][200]['content']['application/json'];
export type SkillsCreateResponse = paths["/skills"]["post"]['responses'][201]['content']['application/json'];
export type SkillsCreateInput = NonNullable<paths["/skills"]["post"]['requestBody']>['content']['application/json'];
export type SkillsGetResponse = paths["/skills/{skill_id}"]["get"]['responses'][200]['content']['application/json'];
export type SkillsUpdateResponse = paths["/skills/{skill_id}"]["patch"]['responses'][200]['content']['application/json'];
export type SkillsUpdateInput = NonNullable<paths["/skills/{skill_id}"]["patch"]['requestBody']>['content']['application/json'];
export type SkillsDeleteResponse = paths["/skills/{skill_id}"]["delete"]['responses'][200]['content']['application/json'];
export type SkillsRestoreResponse = paths["/skills/{skill_id}/undelete"]["post"]['responses'][200]['content']['application/json'];
export type SkillsValidateBundleResponse = paths["/skills/validate-bundle"]["post"]['responses'][200]['content']['application/json'];
export type SkillsValidateBundleInput = NonNullable<paths["/skills/validate-bundle"]["post"]['requestBody']>['content']['application/json'] | (Omit<NonNullable<paths["/skills/validate-bundle"]["post"]['requestBody']>['content']['multipart/form-data'], 'bundle'> & {bundle: ZAIUploadFile});
export type SkillsPublishRevisionResponse = paths["/skills/{skill_id}/revisions"]["post"]['responses'][201]['content']['application/json'];
export type SkillsPublishRevisionInput = NonNullable<paths["/skills/{skill_id}/revisions"]["post"]['requestBody']>['content']['application/json'] | (Omit<NonNullable<paths["/skills/{skill_id}/revisions"]["post"]['requestBody']>['content']['multipart/form-data'], 'bundle'> & {bundle: ZAIUploadFile});
export type SkillsListRevisionsResponse = paths["/skills/{skill_id}/revisions"]["get"]['responses'][200]['content']['application/json'];
export type SkillsListRevisionContentsResponse = paths["/skills/{skill_id}/revisions/{version}/contents"]["get"]['responses'][200]['content']['application/json'];
export type ModelsListResponse = paths["/models"]["get"]['responses'][200]['content']['application/json'];
export type ModelsListQuery = NonNullable<paths["/models"]["get"]['parameters']['query']>;
export type MemoriesListResponse = paths["/memories"]["get"]['responses'][200]['content']['application/json'];
export type MemoriesCreateResponse = paths["/memories"]["post"]['responses'][200]['content']['application/json'];
export type MemoriesCreateInput = NonNullable<paths["/memories"]["post"]['requestBody']>['content']['application/json'];
export type MemoriesGetResponse = paths["/memories/{id}"]["get"]['responses'][200]['content']['application/json'];
export type MemoriesUpdateResponse = paths["/memories/{id}"]["put"]['responses'][200]['content']['application/json'];
export type MemoriesUpdateInput = NonNullable<paths["/memories/{id}"]["put"]['requestBody']>['content']['application/json'];
export type MemoriesDeleteResponse = paths["/memories/{id}"]["delete"]['responses'][200]['content']['application/json'];
export type MemoriesListContentsResponse = paths["/memories/{id}/contents"]["get"]['responses'][200]['content']['application/json'];
export type MemoriesListContentsQuery = NonNullable<paths["/memories/{id}/contents"]["get"]['parameters']['query']>;
export type MemoriesUpsertContentResponse = paths["/memories/{id}/contents"]["post"]['responses'][200]['content']['application/json'];
export type MemoriesUpsertContentInput = NonNullable<paths["/memories/{id}/contents"]["post"]['requestBody']>['content']['application/json'];
export type MemoriesCreateContentsBatchResponse = paths["/memories/{id}/contents/batch"]["post"]['responses'][200]['content']['application/json'];
export type MemoriesCreateContentsBatchInput = NonNullable<paths["/memories/{id}/contents/batch"]["post"]['requestBody']>['content']['application/json'];
export type MemoriesGetContentResponse = paths["/memories/{id}/contents/{content_id}"]["get"]['responses'][200]['content']['application/json'];
export type MemoriesUpdateContentResponse = paths["/memories/{id}/contents/{content_id}"]["put"]['responses'][200]['content']['application/json'];
export type MemoriesUpdateContentInput = NonNullable<paths["/memories/{id}/contents/{content_id}"]["put"]['requestBody']>['content']['application/json'];
export type MemoriesDeleteContentResponse = paths["/memories/{id}/contents/{content_id}"]["delete"]['responses'][200]['content']['application/json'];
export type MemoriesListContentChunksResponse = paths["/memories/{id}/contents/{content_id}/chunks"]["get"]['responses'][200]['content']['application/json'];
export type MemoriesSearchChunksByEmbeddingResponse = paths["/memories/{id}/embeddings-search-chunks"]["post"]['responses'][200]['content']['application/json'];
export type MemoriesSearchChunksByEmbeddingInput = NonNullable<paths["/memories/{id}/embeddings-search-chunks"]["post"]['requestBody']>['content']['application/json'];
export type MemoriesSearchContentsByEmbeddingResponse = paths["/memories/{id}/embeddings-search-contents"]["post"]['responses'][200]['content']['application/json'];
export type MemoriesSearchContentsByEmbeddingInput = NonNullable<paths["/memories/{id}/embeddings-search-contents"]["post"]['requestBody']>['content']['application/json'];
export type MemoriesGetEmbeddingQueueStatsResponse = paths["/memories/queue/stats"]["get"]['responses'][200]['content']['application/json'];
export type MemoriesListContentEmbeddingJobsResponse = paths["/memories/{id}/contents/{content_id}/jobs"]["get"]['responses'][200]['content']['application/json'];

/** Create a stateless API client. Lists retain their server pagination envelopes. */
export function createZAIClient(options: CreateZAIClientOptions) {
  const transport = createTransport(options);
  const baseUrl = new URL(options.baseUrl, globalThis.location?.href).href;
  const client = {
  agents: {
    /** List agents */
    list(options?: ZAIRequestOptions): Promise<AgentsListResponse> { return transport.request<AgentsListResponse>({method: "get", path: "/agents", successStatuses: [200], options}); },
    /** Create agent */
    create(input: AgentsCreateInput, options?: ZAIRequestOptions): Promise<AgentsCreateResponse> { return transport.request<AgentsCreateResponse>({method: "post", path: "/agents", successStatuses: [201], body: input, options}); },
    /** Get agent */
    get(agentId: string, options?: ZAIRequestOptions): Promise<AgentsGetResponse> { return transport.request<AgentsGetResponse>({method: "get", path: "/agents/{agent_id}", successStatuses: [200], pathParams: {"agent_id": agentId}, options}); },
    /** Update agent */
    update(agentId: string, input?: AgentsUpdateInput, options?: ZAIRequestOptions): Promise<AgentsUpdateResponse> { return transport.request<AgentsUpdateResponse>({method: "put", path: "/agents/{agent_id}", successStatuses: [200], pathParams: {"agent_id": agentId}, body: input, options}); },
    /** Delete agent */
    delete(agentId: string, input?: AgentsDeleteInput, options?: ZAIRequestOptions): Promise<AgentsDeleteResponse> { return transport.request<AgentsDeleteResponse>({method: "delete", path: "/agents/{agent_id}", successStatuses: [200], pathParams: {"agent_id": agentId}, body: input, options}); }
  },
  executor: {
    /** Get the current user's public key */
    getPublicKey(agentId: string, options?: ZAIRequestOptions): Promise<ExecutorGetPublicKeyResponse> { return transport.request<ExecutorGetPublicKeyResponse>({method: "get", path: "/agents/{agent_id}/executor/public-key", successStatuses: [200], pathParams: {"agent_id": agentId}, options}); },
    /** Rotate the current user's public key */
    rotatePublicKey(agentId: string, options?: ZAIRequestOptions): Promise<ExecutorRotatePublicKeyResponse> { return transport.request<ExecutorRotatePublicKeyResponse>({method: "post", path: "/agents/{agent_id}/executor/rotate", successStatuses: [200], pathParams: {"agent_id": agentId}, options}); },
    /** Get workspace AGENTS.md */
    getAgentsMarkdown(agentId: string, workspaceId: string, options?: ZAIRequestOptions): Promise<ExecutorGetAgentsMarkdownResponse> { return transport.request<ExecutorGetAgentsMarkdownResponse>({method: "get", path: "/agents/{agent_id}/workspaces/{workspace_id}/executor/AGENTS.md", successStatuses: [200], pathParams: {"agent_id": agentId, "workspace_id": workspaceId}, options}); },
    /** Update workspace AGENTS.md */
    updateAgentsMarkdown(agentId: string, workspaceId: string, input: ExecutorUpdateAgentsMarkdownInput, options?: ZAIRequestOptions): Promise<ExecutorUpdateAgentsMarkdownResponse> { return transport.request<ExecutorUpdateAgentsMarkdownResponse>({method: "put", path: "/agents/{agent_id}/workspaces/{workspace_id}/executor/AGENTS.md", successStatuses: [200], pathParams: {"agent_id": agentId, "workspace_id": workspaceId}, body: input, options}); }
  },
  workspaces: {
    /** List workspaces */
    list(agentId: string, options?: ZAIRequestOptions): Promise<WorkspacesListResponse> { return transport.request<WorkspacesListResponse>({method: "get", path: "/agents/{agent_id}/workspaces", successStatuses: [200], pathParams: {"agent_id": agentId}, options}); },
    /** Create a workspace */
    create(agentId: string, input: WorkspacesCreateInput, options?: ZAIRequestOptions): Promise<WorkspacesCreateResponse> { return transport.request<WorkspacesCreateResponse>({method: "post", path: "/agents/{agent_id}/workspaces", successStatuses: [201], pathParams: {"agent_id": agentId}, body: input, options}); },
    /** Get a workspace */
    get(agentId: string, workspaceId: string, options?: ZAIRequestOptions): Promise<WorkspacesGetResponse> { return transport.request<WorkspacesGetResponse>({method: "get", path: "/agents/{agent_id}/workspaces/{workspace_id}", successStatuses: [200], pathParams: {"agent_id": agentId, "workspace_id": workspaceId}, options}); },
    /** Update a workspace */
    update(agentId: string, workspaceId: string, input?: WorkspacesUpdateInput, options?: ZAIRequestOptions): Promise<WorkspacesUpdateResponse> { return transport.request<WorkspacesUpdateResponse>({method: "patch", path: "/agents/{agent_id}/workspaces/{workspace_id}", successStatuses: [200], pathParams: {"agent_id": agentId, "workspace_id": workspaceId}, body: input, options}); },
    /** Delete a workspace */
    delete(agentId: string, workspaceId: string, options?: ZAIRequestOptions): Promise<WorkspacesDeleteResponse> { return transport.request<WorkspacesDeleteResponse>({method: "delete", path: "/agents/{agent_id}/workspaces/{workspace_id}", successStatuses: [200], pathParams: {"agent_id": agentId, "workspace_id": workspaceId}, options}); }
  },
  repositories: {
    /** List repositories */
    list(agentId: string, workspaceId: string, options?: ZAIRequestOptions): Promise<RepositoriesListResponse> { return transport.request<RepositoriesListResponse>({method: "get", path: "/agents/{agent_id}/workspaces/{workspace_id}/repos", successStatuses: [200], pathParams: {"agent_id": agentId, "workspace_id": workspaceId}, options}); },
    /** Create repository */
    create(agentId: string, workspaceId: string, input?: RepositoriesCreateInput, options?: ZAIRequestOptions): Promise<RepositoriesCreateResponse> { return transport.request<RepositoriesCreateResponse>({method: "post", path: "/agents/{agent_id}/workspaces/{workspace_id}/repos", successStatuses: [201], pathParams: {"agent_id": agentId, "workspace_id": workspaceId}, body: input, options}); },
    /** Get repository */
    get(agentId: string, workspaceId: string, repositoryId: string, options?: ZAIRequestOptions): Promise<RepositoriesGetResponse> { return transport.request<RepositoriesGetResponse>({method: "get", path: "/agents/{agent_id}/workspaces/{workspace_id}/repos/{repository_id}", successStatuses: [200], pathParams: {"agent_id": agentId, "workspace_id": workspaceId, "repository_id": repositoryId}, options}); },
    /** Update repository */
    update(agentId: string, workspaceId: string, repositoryId: string, input?: RepositoriesUpdateInput, options?: ZAIRequestOptions): Promise<RepositoriesUpdateResponse> { return transport.request<RepositoriesUpdateResponse>({method: "patch", path: "/agents/{agent_id}/workspaces/{workspace_id}/repos/{repository_id}", successStatuses: [200], pathParams: {"agent_id": agentId, "workspace_id": workspaceId, "repository_id": repositoryId}, body: input, options}); },
    /** Delete repository */
    delete(agentId: string, workspaceId: string, repositoryId: string, options?: ZAIRequestOptions): Promise<RepositoriesDeleteResponse> { return transport.request<RepositoriesDeleteResponse>({method: "delete", path: "/agents/{agent_id}/workspaces/{workspace_id}/repos/{repository_id}", successStatuses: [200], pathParams: {"agent_id": agentId, "workspace_id": workspaceId, "repository_id": repositoryId}, options}); },
    /** List repository files */
    listFiles(agentId: string, workspaceId: string, repositoryId: string, options?: ZAIRequestOptions): Promise<RepositoriesListFilesResponse> { return transport.request<RepositoriesListFilesResponse>({method: "get", path: "/agents/{agent_id}/workspaces/{workspace_id}/repos/{repository_id}/files", successStatuses: [200], pathParams: {"agent_id": agentId, "workspace_id": workspaceId, "repository_id": repositoryId}, options}); },
    /** Read repository file */
    readFile(agentId: string, workspaceId: string, repositoryId: string, query: RepositoriesReadFileQuery, options?: ZAIRequestOptions): Promise<RepositoriesReadFileResponse> { return transport.request<RepositoriesReadFileResponse>({method: "get", path: "/agents/{agent_id}/workspaces/{workspace_id}/repos/{repository_id}/files/content", successStatuses: [200], pathParams: {"agent_id": agentId, "workspace_id": workspaceId, "repository_id": repositoryId}, query, options}); },
    /** Download repository file */
    downloadFile(agentId: string, workspaceId: string, repositoryId: string, query: RepositoriesDownloadFileQuery, options?: ZAIRequestOptions): Promise<RepositoriesDownloadFileResponse> { return transport.request<RepositoriesDownloadFileResponse>({method: "get", path: "/agents/{agent_id}/workspaces/{workspace_id}/repos/{repository_id}/files/download", successStatuses: [200], pathParams: {"agent_id": agentId, "workspace_id": workspaceId, "repository_id": repositoryId}, query, responseType: 'blob', options}); }
  },
  sessions: {
    /** List sessions */
    list(query?: SessionsListQuery, options?: ZAIRequestOptions): Promise<SessionsListResponse> { return transport.request<SessionsListResponse>({method: "get", path: "/sessions", successStatuses: [200], query, options}); },
    /** List sessions */
    listForAgent(agentId: string, query?: SessionsListForAgentQuery, options?: ZAIRequestOptions): Promise<SessionsListForAgentResponse> { return transport.request<SessionsListForAgentResponse>({method: "get", path: "/agents/{agent_id}/sessions", successStatuses: [200], pathParams: {"agent_id": agentId}, query, options}); },
    /** Create session */
    create(agentId: string, input?: SessionsCreateInput, options?: ZAIRequestOptions): Promise<SessionsCreateResponse> { return transport.request<SessionsCreateResponse>({method: "post", path: "/agents/{agent_id}/sessions", successStatuses: [201], pathParams: {"agent_id": agentId}, body: input, options}); },
    /** Get session */
    get(sessionId: string, options?: ZAIRequestOptions): Promise<SessionsGetResponse> { return transport.request<SessionsGetResponse>({method: "get", path: "/sessions/{session_id}", successStatuses: [200], pathParams: {"session_id": sessionId}, options}); },
    /** Update session */
    update(sessionId: string, input?: SessionsUpdateInput, options?: ZAIRequestOptions): Promise<SessionsUpdateResponse> { return transport.request<SessionsUpdateResponse>({method: "put", path: "/sessions/{session_id}", successStatuses: [200], pathParams: {"session_id": sessionId}, body: input, options}); },
    /** Delete session */
    delete(sessionId: string, options?: ZAIRequestOptions): Promise<SessionsDeleteResponse> { return transport.request<SessionsDeleteResponse>({method: "delete", path: "/sessions/{session_id}", successStatuses: [200], pathParams: {"session_id": sessionId}, options}); },
    /** Reset session context */
    resetContext(sessionId: string, options?: ZAIRequestOptions): Promise<SessionsResetContextResponse> { return transport.request<SessionsResetContextResponse>({method: "post", path: "/sessions/{session_id}/context/reset", successStatuses: [200], pathParams: {"session_id": sessionId}, options}); },
    /** Generate session title */
    generateTitle(sessionId: string, options?: ZAIRequestOptions): Promise<SessionsGenerateTitleResponse> { return transport.request<SessionsGenerateTitleResponse>({method: "post", path: "/sessions/{session_id}/generate-title", successStatuses: [200], pathParams: {"session_id": sessionId}, options}); },
    /** List session files */
    listFiles(sessionId: string, query?: SessionsListFilesQuery, options?: ZAIRequestOptions): Promise<SessionsListFilesResponse> { return transport.request<SessionsListFilesResponse>({method: "get", path: "/sessions/{session_id}/files", successStatuses: [200], pathParams: {"session_id": sessionId}, query, options}); },
    /** Read session file */
    readFile(sessionId: string, query: SessionsReadFileQuery, options?: ZAIRequestOptions): Promise<SessionsReadFileResponse> { return transport.request<SessionsReadFileResponse>({method: "get", path: "/sessions/{session_id}/files/content", successStatuses: [200], pathParams: {"session_id": sessionId}, query, options}); },
    /** Download session file */
    downloadFile(sessionId: string, query: SessionsDownloadFileQuery, options?: ZAIRequestOptions): Promise<SessionsDownloadFileResponse> { return transport.request<SessionsDownloadFileResponse>({method: "get", path: "/sessions/{session_id}/files/download", successStatuses: [200], pathParams: {"session_id": sessionId}, query, responseType: 'blob', options}); },
    /** Upload session file */
    uploadFile(sessionId: string, input: SessionsUploadFileInput, options?: ZAIRequestOptions): Promise<SessionsUploadFileResponse> { return transport.request<SessionsUploadFileResponse>({method: "post", path: "/sessions/{session_id}/files/upload", successStatuses: [200], pathParams: {"session_id": sessionId}, body: input, encoding: 'multipart', options}); },
    /** Generate session images */
    generateImages(sessionId: string, input: SessionsGenerateImagesInput, options?: ZAIRequestOptions): Promise<SessionsGenerateImagesResponse> { return transport.request<SessionsGenerateImagesResponse>({method: "post", path: "/sessions/{session_id}/images/generations", successStatuses: [200], pathParams: {"session_id": sessionId}, body: input, options}); }
  },
  messages: {
    /** Send message */
    send(sessionId: string, input?: MessagesSendInput, options?: ZAIRequestOptions): Promise<MessagesSendResponse> { return transport.request<MessagesSendResponse>({method: "post", path: "/sessions/{session_id}/messages", successStatuses: [200], pathParams: {"session_id": sessionId}, body: {...input, stream: false}, options}); },
    /** Stream full SSE chunks. A done event marks successful completion. */
    async stream(sessionId: string, input?: MessagesSendInput, options?: ZAIRequestOptions): Promise<AsyncIterableIterator<ZAIStreamEvent>> { return parseZAIStream(await transport.request<Response>({method: "post", path: "/sessions/{session_id}/messages", successStatuses: [200], pathParams: {"session_id": sessionId}, body: {...input, stream: true}, options, responseType: 'stream'}), options?.signal); },
    /** List messages */
    list(sessionId: string, options?: ZAIRequestOptions): Promise<MessagesListResponse> { return transport.request<MessagesListResponse>({method: "get", path: "/sessions/{session_id}/messages", successStatuses: [200], pathParams: {"session_id": sessionId}, options}); },
    /** Get message */
    get(messageId: string, options?: ZAIRequestOptions): Promise<MessagesGetResponse> { return transport.request<MessagesGetResponse>({method: "get", path: "/messages/{message_id}", successStatuses: [200], pathParams: {"message_id": messageId}, options}); },
    /** Delete message */
    delete(messageId: string, options?: ZAIRequestOptions): Promise<MessagesDeleteResponse> { return transport.request<MessagesDeleteResponse>({method: "delete", path: "/messages/{message_id}", successStatuses: [200], pathParams: {"message_id": messageId}, options}); },
    /** Delete all messages */
    deleteAll(sessionId: string, options?: ZAIRequestOptions): Promise<MessagesDeleteAllResponse> { return transport.request<MessagesDeleteAllResponse>({method: "delete", path: "/sessions/{session_id}/messages", successStatuses: [200], pathParams: {"session_id": sessionId}, options}); }
  },
  agentSkills: {
    /** List agent skills */
    list(agentId: string, options?: ZAIRequestOptions): Promise<AgentSkillsListResponse> { return transport.request<AgentSkillsListResponse>({method: "get", path: "/agents/{agent_id}/skills", successStatuses: [200], pathParams: {"agent_id": agentId}, options}); },
    /** Mount skill */
    mount(agentId: string, input: AgentSkillsMountInput, options?: ZAIRequestOptions): Promise<AgentSkillsMountResponse> { return transport.request<AgentSkillsMountResponse>({method: "post", path: "/agents/{agent_id}/skills", successStatuses: [201], pathParams: {"agent_id": agentId}, body: input, options}); },
    /** Update mounted skill */
    update(agentId: string, skillId: string, input?: AgentSkillsUpdateInput, options?: ZAIRequestOptions): Promise<AgentSkillsUpdateResponse> { return transport.request<AgentSkillsUpdateResponse>({method: "patch", path: "/agents/{agent_id}/skills/{skill_id}", successStatuses: [200], pathParams: {"agent_id": agentId, "skill_id": skillId}, body: input, options}); },
    /** Unmount skill */
    unmount(agentId: string, skillId: string, options?: ZAIRequestOptions): Promise<AgentSkillsUnmountResponse> { return transport.request<AgentSkillsUnmountResponse>({method: "delete", path: "/agents/{agent_id}/skills/{skill_id}", successStatuses: [200], pathParams: {"agent_id": agentId, "skill_id": skillId}, options}); }
  },
  skills: {
    /** List skills */
    list(options?: ZAIRequestOptions): Promise<SkillsListResponse> { return transport.request<SkillsListResponse>({method: "get", path: "/skills", successStatuses: [200], options}); },
    /** Create skill */
    create(input: SkillsCreateInput, options?: ZAIRequestOptions): Promise<SkillsCreateResponse> { return transport.request<SkillsCreateResponse>({method: "post", path: "/skills", successStatuses: [201], body: input, options}); },
    /** Get skill */
    get(skillId: string, options?: ZAIRequestOptions): Promise<SkillsGetResponse> { return transport.request<SkillsGetResponse>({method: "get", path: "/skills/{skill_id}", successStatuses: [200], pathParams: {"skill_id": skillId}, options}); },
    /** Update skill */
    update(skillId: string, input?: SkillsUpdateInput, options?: ZAIRequestOptions): Promise<SkillsUpdateResponse> { return transport.request<SkillsUpdateResponse>({method: "patch", path: "/skills/{skill_id}", successStatuses: [200], pathParams: {"skill_id": skillId}, body: input, options}); },
    /** Delete skill */
    delete(skillId: string, options?: ZAIRequestOptions): Promise<SkillsDeleteResponse> { return transport.request<SkillsDeleteResponse>({method: "delete", path: "/skills/{skill_id}", successStatuses: [200], pathParams: {"skill_id": skillId}, options}); },
    /** Restore skill */
    restore(skillId: string, options?: ZAIRequestOptions): Promise<SkillsRestoreResponse> { return transport.request<SkillsRestoreResponse>({method: "post", path: "/skills/{skill_id}/undelete", successStatuses: [200], pathParams: {"skill_id": skillId}, options}); },
    /** Validate skill bundle */
    validateBundle(input: SkillsValidateBundleInput, options?: ZAIRequestOptions): Promise<SkillsValidateBundleResponse> { return transport.request<SkillsValidateBundleResponse>({method: "post", path: "/skills/validate-bundle", successStatuses: [200], body: input, encoding: 'bundle', options}); },
    /** Publish revision */
    publishRevision(skillId: string, input: SkillsPublishRevisionInput, options?: ZAIRequestOptions): Promise<SkillsPublishRevisionResponse> { return transport.request<SkillsPublishRevisionResponse>({method: "post", path: "/skills/{skill_id}/revisions", successStatuses: [201], pathParams: {"skill_id": skillId}, body: input, encoding: 'bundle', options}); },
    /** List revisions */
    listRevisions(skillId: string, options?: ZAIRequestOptions): Promise<SkillsListRevisionsResponse> { return transport.request<SkillsListRevisionsResponse>({method: "get", path: "/skills/{skill_id}/revisions", successStatuses: [200], pathParams: {"skill_id": skillId}, options}); },
    /** List revision contents */
    listRevisionContents(skillId: string, version: string, options?: ZAIRequestOptions): Promise<SkillsListRevisionContentsResponse> { return transport.request<SkillsListRevisionContentsResponse>({method: "get", path: "/skills/{skill_id}/revisions/{version}/contents", successStatuses: [200], pathParams: {"skill_id": skillId, "version": version}, options}); }
  },
  models: {
    /** List models */
    async list(query?: ModelsListQuery, options?: ZAIRequestOptions): Promise<ModelsListResponse> {
      const result = await transport.request<ModelsListResponse>({method: "get", path: "/models", successStatuses: [200], query, options});
      const normalized = Array.isArray(result) ? {models: result} : result;
      if (!normalized || !Array.isArray(normalized.models) || normalized.models.some(model => !model || typeof model.id !== 'string')) throw new ZAIClientError('invalid-response', 'Invalid model list response.');
      return normalized;
    }
  },
  memories: {
    /** List memory collections */
    list(options?: ZAIRequestOptions): Promise<MemoriesListResponse> { return transport.request<MemoriesListResponse>({method: "get", path: "/memories", successStatuses: [200], options}); },
    /** Create a memory collection */
    create(input: MemoriesCreateInput, options?: ZAIRequestOptions): Promise<MemoriesCreateResponse> { return transport.request<MemoriesCreateResponse>({method: "post", path: "/memories", successStatuses: [200], body: input, options}); },
    /** Get a memory collection */
    get(id: string, options?: ZAIRequestOptions): Promise<MemoriesGetResponse> { return transport.request<MemoriesGetResponse>({method: "get", path: "/memories/{id}", successStatuses: [200], pathParams: {"id": id}, options}); },
    /** Update a memory collection */
    update(id: string, input: MemoriesUpdateInput, options?: ZAIRequestOptions): Promise<MemoriesUpdateResponse> { return transport.request<MemoriesUpdateResponse>({method: "put", path: "/memories/{id}", successStatuses: [200], pathParams: {"id": id}, body: input, options}); },
    /** Delete a memory collection */
    delete(id: string, options?: ZAIRequestOptions): Promise<MemoriesDeleteResponse> { return transport.request<MemoriesDeleteResponse>({method: "delete", path: "/memories/{id}", successStatuses: [200], pathParams: {"id": id}, options}); },
    /** List memory contents */
    listContents(id: string, query?: MemoriesListContentsQuery, options?: ZAIRequestOptions): Promise<MemoriesListContentsResponse> { return transport.request<MemoriesListContentsResponse>({method: "get", path: "/memories/{id}/contents", successStatuses: [200], pathParams: {"id": id}, query, options}); },
    /** Create or update memory content */
    upsertContent(id: string, input: MemoriesUpsertContentInput, options?: ZAIRequestOptions): Promise<MemoriesUpsertContentResponse> { return transport.request<MemoriesUpsertContentResponse>({method: "post", path: "/memories/{id}/contents", successStatuses: [200], pathParams: {"id": id}, body: input, options}); },
    /** Create memory contents in batch */
    createContentsBatch(id: string, input: MemoriesCreateContentsBatchInput, options?: ZAIRequestOptions): Promise<MemoriesCreateContentsBatchResponse> { return transport.request<MemoriesCreateContentsBatchResponse>({method: "post", path: "/memories/{id}/contents/batch", successStatuses: [200], pathParams: {"id": id}, body: input, options}); },
    /** Get memory content */
    getContent(id: string, contentId: string, options?: ZAIRequestOptions): Promise<MemoriesGetContentResponse> { return transport.request<MemoriesGetContentResponse>({method: "get", path: "/memories/{id}/contents/{content_id}", successStatuses: [200], pathParams: {"id": id, "content_id": contentId}, options}); },
    /** Update memory content */
    updateContent(id: string, contentId: string, input: MemoriesUpdateContentInput, options?: ZAIRequestOptions): Promise<MemoriesUpdateContentResponse> { return transport.request<MemoriesUpdateContentResponse>({method: "put", path: "/memories/{id}/contents/{content_id}", successStatuses: [200], pathParams: {"id": id, "content_id": contentId}, body: input, options}); },
    /** Delete memory content */
    deleteContent(id: string, contentId: string, options?: ZAIRequestOptions): Promise<MemoriesDeleteContentResponse> { return transport.request<MemoriesDeleteContentResponse>({method: "delete", path: "/memories/{id}/contents/{content_id}", successStatuses: [200], pathParams: {"id": id, "content_id": contentId}, options}); },
    /** List content chunks */
    listContentChunks(id: string, contentId: string, options?: ZAIRequestOptions): Promise<MemoriesListContentChunksResponse> { return transport.request<MemoriesListContentChunksResponse>({method: "get", path: "/memories/{id}/contents/{content_id}/chunks", successStatuses: [200], pathParams: {"id": id, "content_id": contentId}, options}); },
    /** Search memory chunks by embedding */
    searchChunksByEmbedding(id: string, input: MemoriesSearchChunksByEmbeddingInput, options?: ZAIRequestOptions): Promise<MemoriesSearchChunksByEmbeddingResponse> { return transport.request<MemoriesSearchChunksByEmbeddingResponse>({method: "post", path: "/memories/{id}/embeddings-search-chunks", successStatuses: [200], pathParams: {"id": id}, body: input, options}); },
    /** Search memory contents by embedding */
    searchContentsByEmbedding(id: string, input: MemoriesSearchContentsByEmbeddingInput, options?: ZAIRequestOptions): Promise<MemoriesSearchContentsByEmbeddingResponse> { return transport.request<MemoriesSearchContentsByEmbeddingResponse>({method: "post", path: "/memories/{id}/embeddings-search-contents", successStatuses: [200], pathParams: {"id": id}, body: input, options}); },
    /** Get embedding queue status */
    getEmbeddingQueueStats(options?: ZAIRequestOptions): Promise<MemoriesGetEmbeddingQueueStatsResponse> { return transport.request<MemoriesGetEmbeddingQueueStatsResponse>({method: "get", path: "/memories/queue/stats", successStatuses: [200], options}); },
    /** List content embedding jobs */
    listContentEmbeddingJobs(id: string, contentId: string, options?: ZAIRequestOptions): Promise<MemoriesListContentEmbeddingJobsResponse> { return transport.request<MemoriesListContentEmbeddingJobsResponse>({method: "get", path: "/memories/{id}/contents/{content_id}/jobs", successStatuses: [200], pathParams: {"id": id, "content_id": contentId}, options}); }
  }
  };
  return {
    ...client,
    /** Check connection and capabilities; opt into a temporary chat probe with chat: true. */
    doctor(options?: ZAIDoctorOptions): Promise<ZAIDoctorResult> { return runZAIDoctor(client, baseUrl, options); },
  };
}

export type ZAIClient = ReturnType<typeof createZAIClient>;
