/** Generated by pnpm generate:api from zai-openapi.json. Do not edit directly. */
/** Operation manifest used by contract tests and diagnostics. */
export const ZAI_OPERATIONS = [
  {
    "group": "agents",
    "name": "list",
    "method": "get",
    "path": "/agents",
    "pathParams": [],
    "query": [],
    "hasBody": false,
    "encoding": "json",
    "responseType": "json",
    "statuses": [
      200
    ]
  },
  {
    "group": "agents",
    "name": "create",
    "method": "post",
    "path": "/agents",
    "pathParams": [],
    "query": [],
    "hasBody": true,
    "encoding": "json",
    "responseType": "json",
    "statuses": [
      201
    ]
  },
  {
    "group": "agents",
    "name": "get",
    "method": "get",
    "path": "/agents/{agent_id}",
    "pathParams": [
      "agent_id"
    ],
    "query": [],
    "hasBody": false,
    "encoding": "json",
    "responseType": "json",
    "statuses": [
      200
    ]
  },
  {
    "group": "agents",
    "name": "update",
    "method": "put",
    "path": "/agents/{agent_id}",
    "pathParams": [
      "agent_id"
    ],
    "query": [],
    "hasBody": true,
    "encoding": "json",
    "responseType": "json",
    "statuses": [
      200
    ]
  },
  {
    "group": "agents",
    "name": "delete",
    "method": "delete",
    "path": "/agents/{agent_id}",
    "pathParams": [
      "agent_id"
    ],
    "query": [],
    "hasBody": true,
    "encoding": "json",
    "responseType": "json",
    "statuses": [
      200
    ]
  },
  {
    "group": "executor",
    "name": "getPublicKey",
    "method": "get",
    "path": "/agents/{agent_id}/executor/public-key",
    "pathParams": [
      "agent_id"
    ],
    "query": [],
    "hasBody": false,
    "encoding": "json",
    "responseType": "json",
    "statuses": [
      200
    ]
  },
  {
    "group": "executor",
    "name": "rotatePublicKey",
    "method": "post",
    "path": "/agents/{agent_id}/executor/rotate",
    "pathParams": [
      "agent_id"
    ],
    "query": [],
    "hasBody": false,
    "encoding": "json",
    "responseType": "json",
    "statuses": [
      200
    ]
  },
  {
    "group": "executor",
    "name": "getAgentsMarkdown",
    "method": "get",
    "path": "/agents/{agent_id}/workspaces/{workspace_id}/executor/AGENTS.md",
    "pathParams": [
      "agent_id",
      "workspace_id"
    ],
    "query": [],
    "hasBody": false,
    "encoding": "json",
    "responseType": "json",
    "statuses": [
      200
    ]
  },
  {
    "group": "executor",
    "name": "updateAgentsMarkdown",
    "method": "put",
    "path": "/agents/{agent_id}/workspaces/{workspace_id}/executor/AGENTS.md",
    "pathParams": [
      "agent_id",
      "workspace_id"
    ],
    "query": [],
    "hasBody": true,
    "encoding": "json",
    "responseType": "json",
    "statuses": [
      200
    ]
  },
  {
    "group": "workspaces",
    "name": "list",
    "method": "get",
    "path": "/agents/{agent_id}/workspaces",
    "pathParams": [
      "agent_id"
    ],
    "query": [],
    "hasBody": false,
    "encoding": "json",
    "responseType": "json",
    "statuses": [
      200
    ]
  },
  {
    "group": "workspaces",
    "name": "create",
    "method": "post",
    "path": "/agents/{agent_id}/workspaces",
    "pathParams": [
      "agent_id"
    ],
    "query": [],
    "hasBody": true,
    "encoding": "json",
    "responseType": "json",
    "statuses": [
      201
    ]
  },
  {
    "group": "workspaces",
    "name": "get",
    "method": "get",
    "path": "/agents/{agent_id}/workspaces/{workspace_id}",
    "pathParams": [
      "agent_id",
      "workspace_id"
    ],
    "query": [],
    "hasBody": false,
    "encoding": "json",
    "responseType": "json",
    "statuses": [
      200
    ]
  },
  {
    "group": "workspaces",
    "name": "update",
    "method": "patch",
    "path": "/agents/{agent_id}/workspaces/{workspace_id}",
    "pathParams": [
      "agent_id",
      "workspace_id"
    ],
    "query": [],
    "hasBody": true,
    "encoding": "json",
    "responseType": "json",
    "statuses": [
      200
    ]
  },
  {
    "group": "workspaces",
    "name": "delete",
    "method": "delete",
    "path": "/agents/{agent_id}/workspaces/{workspace_id}",
    "pathParams": [
      "agent_id",
      "workspace_id"
    ],
    "query": [],
    "hasBody": false,
    "encoding": "json",
    "responseType": "json",
    "statuses": [
      200
    ]
  },
  {
    "group": "repositories",
    "name": "list",
    "method": "get",
    "path": "/agents/{agent_id}/workspaces/{workspace_id}/repos",
    "pathParams": [
      "agent_id",
      "workspace_id"
    ],
    "query": [],
    "hasBody": false,
    "encoding": "json",
    "responseType": "json",
    "statuses": [
      200
    ]
  },
  {
    "group": "repositories",
    "name": "create",
    "method": "post",
    "path": "/agents/{agent_id}/workspaces/{workspace_id}/repos",
    "pathParams": [
      "agent_id",
      "workspace_id"
    ],
    "query": [],
    "hasBody": true,
    "encoding": "json",
    "responseType": "json",
    "statuses": [
      201
    ]
  },
  {
    "group": "repositories",
    "name": "get",
    "method": "get",
    "path": "/agents/{agent_id}/workspaces/{workspace_id}/repos/{repository_id}",
    "pathParams": [
      "agent_id",
      "workspace_id",
      "repository_id"
    ],
    "query": [],
    "hasBody": false,
    "encoding": "json",
    "responseType": "json",
    "statuses": [
      200
    ]
  },
  {
    "group": "repositories",
    "name": "update",
    "method": "patch",
    "path": "/agents/{agent_id}/workspaces/{workspace_id}/repos/{repository_id}",
    "pathParams": [
      "agent_id",
      "workspace_id",
      "repository_id"
    ],
    "query": [],
    "hasBody": true,
    "encoding": "json",
    "responseType": "json",
    "statuses": [
      200
    ]
  },
  {
    "group": "repositories",
    "name": "delete",
    "method": "delete",
    "path": "/agents/{agent_id}/workspaces/{workspace_id}/repos/{repository_id}",
    "pathParams": [
      "agent_id",
      "workspace_id",
      "repository_id"
    ],
    "query": [],
    "hasBody": false,
    "encoding": "json",
    "responseType": "json",
    "statuses": [
      200
    ]
  },
  {
    "group": "repositories",
    "name": "listFiles",
    "method": "get",
    "path": "/agents/{agent_id}/workspaces/{workspace_id}/repos/{repository_id}/files",
    "pathParams": [
      "agent_id",
      "workspace_id",
      "repository_id"
    ],
    "query": [],
    "hasBody": false,
    "encoding": "json",
    "responseType": "json",
    "statuses": [
      200
    ]
  },
  {
    "group": "repositories",
    "name": "readFile",
    "method": "get",
    "path": "/agents/{agent_id}/workspaces/{workspace_id}/repos/{repository_id}/files/content",
    "pathParams": [
      "agent_id",
      "workspace_id",
      "repository_id"
    ],
    "query": [
      "path"
    ],
    "hasBody": false,
    "encoding": "json",
    "responseType": "json",
    "statuses": [
      200
    ]
  },
  {
    "group": "repositories",
    "name": "downloadFile",
    "method": "get",
    "path": "/agents/{agent_id}/workspaces/{workspace_id}/repos/{repository_id}/files/download",
    "pathParams": [
      "agent_id",
      "workspace_id",
      "repository_id"
    ],
    "query": [
      "path"
    ],
    "hasBody": false,
    "encoding": "json",
    "responseType": "blob",
    "statuses": [
      200
    ]
  },
  {
    "group": "sessions",
    "name": "list",
    "method": "get",
    "path": "/sessions",
    "pathParams": [],
    "query": [
      "category",
      "agent_id",
      "model",
      "page",
      "page_size"
    ],
    "hasBody": false,
    "encoding": "json",
    "responseType": "json",
    "statuses": [
      200
    ]
  },
  {
    "group": "sessions",
    "name": "listForAgent",
    "method": "get",
    "path": "/agents/{agent_id}/sessions",
    "pathParams": [
      "agent_id"
    ],
    "query": [
      "category",
      "agent_id",
      "model",
      "page",
      "page_size"
    ],
    "hasBody": false,
    "encoding": "json",
    "responseType": "json",
    "statuses": [
      200
    ]
  },
  {
    "group": "sessions",
    "name": "create",
    "method": "post",
    "path": "/agents/{agent_id}/sessions",
    "pathParams": [
      "agent_id"
    ],
    "query": [],
    "hasBody": true,
    "encoding": "json",
    "responseType": "json",
    "statuses": [
      201
    ]
  },
  {
    "group": "sessions",
    "name": "get",
    "method": "get",
    "path": "/sessions/{session_id}",
    "pathParams": [
      "session_id"
    ],
    "query": [],
    "hasBody": false,
    "encoding": "json",
    "responseType": "json",
    "statuses": [
      200
    ]
  },
  {
    "group": "sessions",
    "name": "update",
    "method": "put",
    "path": "/sessions/{session_id}",
    "pathParams": [
      "session_id"
    ],
    "query": [],
    "hasBody": true,
    "encoding": "json",
    "responseType": "json",
    "statuses": [
      200
    ]
  },
  {
    "group": "sessions",
    "name": "delete",
    "method": "delete",
    "path": "/sessions/{session_id}",
    "pathParams": [
      "session_id"
    ],
    "query": [],
    "hasBody": false,
    "encoding": "json",
    "responseType": "json",
    "statuses": [
      200
    ]
  },
  {
    "group": "sessions",
    "name": "resetContext",
    "method": "post",
    "path": "/sessions/{session_id}/context/reset",
    "pathParams": [
      "session_id"
    ],
    "query": [],
    "hasBody": false,
    "encoding": "json",
    "responseType": "json",
    "statuses": [
      200
    ]
  },
  {
    "group": "sessions",
    "name": "generateTitle",
    "method": "post",
    "path": "/sessions/{session_id}/generate-title",
    "pathParams": [
      "session_id"
    ],
    "query": [],
    "hasBody": false,
    "encoding": "json",
    "responseType": "json",
    "statuses": [
      200
    ]
  },
  {
    "group": "sessions",
    "name": "listFiles",
    "method": "get",
    "path": "/sessions/{session_id}/files",
    "pathParams": [
      "session_id"
    ],
    "query": [
      "path"
    ],
    "hasBody": false,
    "encoding": "json",
    "responseType": "json",
    "statuses": [
      200
    ]
  },
  {
    "group": "sessions",
    "name": "readFile",
    "method": "get",
    "path": "/sessions/{session_id}/files/content",
    "pathParams": [
      "session_id"
    ],
    "query": [
      "path"
    ],
    "hasBody": false,
    "encoding": "json",
    "responseType": "json",
    "statuses": [
      200
    ]
  },
  {
    "group": "sessions",
    "name": "downloadFile",
    "method": "get",
    "path": "/sessions/{session_id}/files/download",
    "pathParams": [
      "session_id"
    ],
    "query": [
      "path"
    ],
    "hasBody": false,
    "encoding": "json",
    "responseType": "blob",
    "statuses": [
      200
    ]
  },
  {
    "group": "sessions",
    "name": "uploadFile",
    "method": "post",
    "path": "/sessions/{session_id}/files/upload",
    "pathParams": [
      "session_id"
    ],
    "query": [],
    "hasBody": true,
    "encoding": "multipart",
    "responseType": "json",
    "statuses": [
      200
    ]
  },
  {
    "group": "sessions",
    "name": "generateImages",
    "method": "post",
    "path": "/sessions/{session_id}/images/generations",
    "pathParams": [
      "session_id"
    ],
    "query": [],
    "hasBody": true,
    "encoding": "json",
    "responseType": "json",
    "statuses": [
      200
    ]
  },
  {
    "group": "messages",
    "name": "send",
    "method": "post",
    "path": "/sessions/{session_id}/messages",
    "pathParams": [
      "session_id"
    ],
    "query": [],
    "hasBody": true,
    "encoding": "json",
    "responseType": "json",
    "statuses": [
      200
    ]
  },
  {
    "group": "messages",
    "name": "list",
    "method": "get",
    "path": "/sessions/{session_id}/messages",
    "pathParams": [
      "session_id"
    ],
    "query": [],
    "hasBody": false,
    "encoding": "json",
    "responseType": "json",
    "statuses": [
      200
    ]
  },
  {
    "group": "messages",
    "name": "get",
    "method": "get",
    "path": "/messages/{message_id}",
    "pathParams": [
      "message_id"
    ],
    "query": [],
    "hasBody": false,
    "encoding": "json",
    "responseType": "json",
    "statuses": [
      200
    ]
  },
  {
    "group": "messages",
    "name": "delete",
    "method": "delete",
    "path": "/messages/{message_id}",
    "pathParams": [
      "message_id"
    ],
    "query": [],
    "hasBody": false,
    "encoding": "json",
    "responseType": "json",
    "statuses": [
      200
    ]
  },
  {
    "group": "messages",
    "name": "deleteAll",
    "method": "delete",
    "path": "/sessions/{session_id}/messages",
    "pathParams": [
      "session_id"
    ],
    "query": [],
    "hasBody": false,
    "encoding": "json",
    "responseType": "json",
    "statuses": [
      200
    ]
  },
  {
    "group": "agentSkills",
    "name": "list",
    "method": "get",
    "path": "/agents/{agent_id}/skills",
    "pathParams": [
      "agent_id"
    ],
    "query": [],
    "hasBody": false,
    "encoding": "json",
    "responseType": "json",
    "statuses": [
      200
    ]
  },
  {
    "group": "agentSkills",
    "name": "mount",
    "method": "post",
    "path": "/agents/{agent_id}/skills",
    "pathParams": [
      "agent_id"
    ],
    "query": [],
    "hasBody": true,
    "encoding": "json",
    "responseType": "json",
    "statuses": [
      201
    ]
  },
  {
    "group": "agentSkills",
    "name": "update",
    "method": "patch",
    "path": "/agents/{agent_id}/skills/{skill_id}",
    "pathParams": [
      "agent_id",
      "skill_id"
    ],
    "query": [],
    "hasBody": true,
    "encoding": "json",
    "responseType": "json",
    "statuses": [
      200
    ]
  },
  {
    "group": "agentSkills",
    "name": "unmount",
    "method": "delete",
    "path": "/agents/{agent_id}/skills/{skill_id}",
    "pathParams": [
      "agent_id",
      "skill_id"
    ],
    "query": [],
    "hasBody": false,
    "encoding": "json",
    "responseType": "json",
    "statuses": [
      200
    ]
  },
  {
    "group": "skills",
    "name": "list",
    "method": "get",
    "path": "/skills",
    "pathParams": [],
    "query": [],
    "hasBody": false,
    "encoding": "json",
    "responseType": "json",
    "statuses": [
      200
    ]
  },
  {
    "group": "skills",
    "name": "create",
    "method": "post",
    "path": "/skills",
    "pathParams": [],
    "query": [],
    "hasBody": true,
    "encoding": "json",
    "responseType": "json",
    "statuses": [
      201
    ]
  },
  {
    "group": "skills",
    "name": "get",
    "method": "get",
    "path": "/skills/{skill_id}",
    "pathParams": [
      "skill_id"
    ],
    "query": [],
    "hasBody": false,
    "encoding": "json",
    "responseType": "json",
    "statuses": [
      200
    ]
  },
  {
    "group": "skills",
    "name": "update",
    "method": "patch",
    "path": "/skills/{skill_id}",
    "pathParams": [
      "skill_id"
    ],
    "query": [],
    "hasBody": true,
    "encoding": "json",
    "responseType": "json",
    "statuses": [
      200
    ]
  },
  {
    "group": "skills",
    "name": "delete",
    "method": "delete",
    "path": "/skills/{skill_id}",
    "pathParams": [
      "skill_id"
    ],
    "query": [],
    "hasBody": false,
    "encoding": "json",
    "responseType": "json",
    "statuses": [
      200
    ]
  },
  {
    "group": "skills",
    "name": "restore",
    "method": "post",
    "path": "/skills/{skill_id}/undelete",
    "pathParams": [
      "skill_id"
    ],
    "query": [],
    "hasBody": false,
    "encoding": "json",
    "responseType": "json",
    "statuses": [
      200
    ]
  },
  {
    "group": "skills",
    "name": "validateBundle",
    "method": "post",
    "path": "/skills/validate-bundle",
    "pathParams": [],
    "query": [],
    "hasBody": true,
    "encoding": "bundle",
    "responseType": "json",
    "statuses": [
      200
    ]
  },
  {
    "group": "skills",
    "name": "publishRevision",
    "method": "post",
    "path": "/skills/{skill_id}/revisions",
    "pathParams": [
      "skill_id"
    ],
    "query": [],
    "hasBody": true,
    "encoding": "bundle",
    "responseType": "json",
    "statuses": [
      201
    ]
  },
  {
    "group": "skills",
    "name": "listRevisions",
    "method": "get",
    "path": "/skills/{skill_id}/revisions",
    "pathParams": [
      "skill_id"
    ],
    "query": [],
    "hasBody": false,
    "encoding": "json",
    "responseType": "json",
    "statuses": [
      200
    ]
  },
  {
    "group": "skills",
    "name": "listRevisionContents",
    "method": "get",
    "path": "/skills/{skill_id}/revisions/{version}/contents",
    "pathParams": [
      "skill_id",
      "version"
    ],
    "query": [],
    "hasBody": false,
    "encoding": "json",
    "responseType": "json",
    "statuses": [
      200
    ]
  },
  {
    "group": "models",
    "name": "list",
    "method": "get",
    "path": "/models",
    "pathParams": [],
    "query": [
      "all"
    ],
    "hasBody": false,
    "encoding": "json",
    "responseType": "json",
    "statuses": [
      200
    ]
  },
  {
    "group": "memories",
    "name": "list",
    "method": "get",
    "path": "/memories",
    "pathParams": [],
    "query": [],
    "hasBody": false,
    "encoding": "json",
    "responseType": "json",
    "statuses": [
      200
    ]
  },
  {
    "group": "memories",
    "name": "create",
    "method": "post",
    "path": "/memories",
    "pathParams": [],
    "query": [],
    "hasBody": true,
    "encoding": "json",
    "responseType": "json",
    "statuses": [
      200
    ]
  },
  {
    "group": "memories",
    "name": "get",
    "method": "get",
    "path": "/memories/{id}",
    "pathParams": [
      "id"
    ],
    "query": [],
    "hasBody": false,
    "encoding": "json",
    "responseType": "json",
    "statuses": [
      200
    ]
  },
  {
    "group": "memories",
    "name": "update",
    "method": "put",
    "path": "/memories/{id}",
    "pathParams": [
      "id"
    ],
    "query": [],
    "hasBody": true,
    "encoding": "json",
    "responseType": "json",
    "statuses": [
      200
    ]
  },
  {
    "group": "memories",
    "name": "delete",
    "method": "delete",
    "path": "/memories/{id}",
    "pathParams": [
      "id"
    ],
    "query": [],
    "hasBody": false,
    "encoding": "json",
    "responseType": "json",
    "statuses": [
      200
    ]
  },
  {
    "group": "memories",
    "name": "listContents",
    "method": "get",
    "path": "/memories/{id}/contents",
    "pathParams": [
      "id"
    ],
    "query": [
      "type",
      "keywords"
    ],
    "hasBody": false,
    "encoding": "json",
    "responseType": "json",
    "statuses": [
      200
    ]
  },
  {
    "group": "memories",
    "name": "upsertContent",
    "method": "post",
    "path": "/memories/{id}/contents",
    "pathParams": [
      "id"
    ],
    "query": [],
    "hasBody": true,
    "encoding": "json",
    "responseType": "json",
    "statuses": [
      200
    ]
  },
  {
    "group": "memories",
    "name": "createContentsBatch",
    "method": "post",
    "path": "/memories/{id}/contents/batch",
    "pathParams": [
      "id"
    ],
    "query": [],
    "hasBody": true,
    "encoding": "json",
    "responseType": "json",
    "statuses": [
      200
    ]
  },
  {
    "group": "memories",
    "name": "getContent",
    "method": "get",
    "path": "/memories/{id}/contents/{content_id}",
    "pathParams": [
      "id",
      "content_id"
    ],
    "query": [],
    "hasBody": false,
    "encoding": "json",
    "responseType": "json",
    "statuses": [
      200
    ]
  },
  {
    "group": "memories",
    "name": "updateContent",
    "method": "put",
    "path": "/memories/{id}/contents/{content_id}",
    "pathParams": [
      "id",
      "content_id"
    ],
    "query": [],
    "hasBody": true,
    "encoding": "json",
    "responseType": "json",
    "statuses": [
      200
    ]
  },
  {
    "group": "memories",
    "name": "deleteContent",
    "method": "delete",
    "path": "/memories/{id}/contents/{content_id}",
    "pathParams": [
      "id",
      "content_id"
    ],
    "query": [],
    "hasBody": false,
    "encoding": "json",
    "responseType": "json",
    "statuses": [
      200
    ]
  },
  {
    "group": "memories",
    "name": "listContentChunks",
    "method": "get",
    "path": "/memories/{id}/contents/{content_id}/chunks",
    "pathParams": [
      "id",
      "content_id"
    ],
    "query": [],
    "hasBody": false,
    "encoding": "json",
    "responseType": "json",
    "statuses": [
      200
    ]
  },
  {
    "group": "memories",
    "name": "searchChunksByEmbedding",
    "method": "post",
    "path": "/memories/{id}/embeddings-search-chunks",
    "pathParams": [
      "id"
    ],
    "query": [],
    "hasBody": true,
    "encoding": "json",
    "responseType": "json",
    "statuses": [
      200
    ]
  },
  {
    "group": "memories",
    "name": "searchContentsByEmbedding",
    "method": "post",
    "path": "/memories/{id}/embeddings-search-contents",
    "pathParams": [
      "id"
    ],
    "query": [],
    "hasBody": true,
    "encoding": "json",
    "responseType": "json",
    "statuses": [
      200
    ]
  },
  {
    "group": "memories",
    "name": "getEmbeddingQueueStats",
    "method": "get",
    "path": "/memories/queue/stats",
    "pathParams": [],
    "query": [],
    "hasBody": false,
    "encoding": "json",
    "responseType": "json",
    "statuses": [
      200
    ]
  },
  {
    "group": "memories",
    "name": "listContentEmbeddingJobs",
    "method": "get",
    "path": "/memories/{id}/contents/{content_id}/jobs",
    "pathParams": [
      "id",
      "content_id"
    ],
    "query": [],
    "hasBody": false,
    "encoding": "json",
    "responseType": "json",
    "statuses": [
      200
    ]
  }
] as const;
